package constants

const (
	PingCmd        = "PING"
	SetCmd         = "SET"
	MSetCmd        = "MSET"
	SetRangeCmd    = "SETRANGE"
	GetCmd         = "GET"
	MGetCmd        = "MGET"
	DelCmd         = "DEL"
	GetDelCmd      = "GETDEL"
	GetRangeCmd    = "GETRANGE"
	GetExCmd       = "GETEX"
	IncrCmd        = "INCR"
	IncrByCmd      = "INCRBY"
	IncrByFloatCmd = "INCRBYFLOAT"
	DecrCmd        = "DECR"
	DecrByCmd      = "DECRBY"
	AppendCmd      = "APPEND"
	CommandCmd     = "COMMAND"
	StrlenCmd      = "STRLEN"
	MSetNx         = "MSETNX"
	LPushCmd       = "LPUSH"
	LLenCmd        = "LLEN"
	LPopCmd        = "LPOP"
)
