name: Update Docker Image in DockerHub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the Git tag
        id: git_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Build and Tag Docker Image
        run: |
          docker build -t gores . && \
          docker tag gores "${{ secrets.DOCKERHUB_USERNAME }}/gores:${{ steps.git_tag.outputs.tag }}"

      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/gores:${{ steps.git_tag.outputs.tag }}"

      - name: Update Latest Tag
        run: |
          docker tag "${{ secrets.DOCKERHUB_USERNAME }}/gores:${{ steps.git_tag.outputs.tag }}" "${{ secrets.DOCKERHUB_USERNAME }}/gores:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/gores:latest"
